version: "3"

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus_data:/nexus-data
    networks:
      - traefik-proxy
      - default
      
    # Control the number of instances deployed
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.nexus.entrypoints=web
        - traefik.http.services.nexus.loadbalancer.server.port=8081
        - traefik.http.routers.nexus.rule=Host(`nexus.domain.com`)
        # configure port for hosted docker repository in Nexus
        - traefik.http.services.labdocker.loadbalancer.server.port=8083
        - traefik.http.routers.labdocker.rule=Host(`docker.domain.com`)
        - traefik.docker.network=traefik-proxy

networks:
  traefik-proxy:
    external: true

volumes:
  nexus_data:

