version: "3"

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus-data:/nexus-data
    networks:
      - traefik-proxy
      - default
      
    # Control the number of instances deployed
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.nexus_insecure.entrypoints=http
        - traefik.http.routers.nexus_insecure.rule=Host(`nexus.domain.com`)
        #- traefik.http.routers.nexus_insecure.middlewares=redirect@file

        - traefik.http.routers.nexus.entrypoints=https
        - traefik.http.routers.nexus.rule=Host(`nexus.domain.com`)
        #- traefik.http.routers.nexus.tls.certresolver=letsencrypt
        - traefik.http.services.nexus.loadbalancer.server.port=8081
        - traefik.docker.network=traefik-proxy

networks:
  traefik-proxy:
    external: true

volumes:
  nexus-data:

