version: "3"

services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik-proxy
      - default
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer_insecure.entrypoints=web
        - traefik.http.routers.portainer_insecure.rule=Host(`portainer.domain.com`)
        #- traefik.http.routers.portainer_insecure.middlewares=redirect@file

        - traefik.http.routers.portainer.entrypoints=web-secure
        - traefik.http.routers.portainer.rule=Host(`portainer.domain.com`)
        #- traefik.http.routers.portainer.tls.certresolver=letsencrypt
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.docker.network=traefik-proxy
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
networks:
  traefik-proxy:
    external: true

volumes:
  portainer_data:
